baseURL = "beta.baxtrbuids.com"
languageCode = "en-us"
title = "Baxtr Builds"
themesDir = "../.."
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Baxtr Builds was a Computer Hardware company specializing in eSports Gaming builds."
    meta_og_title = "Baxtr Builds"
    meta_og_type = "website"
    meta_og_url = "https://beta.baxtrbuids.com"
    meta_og_image = ""
    meta_og_description = "Baxtr Builds was a Computer Hardware company specializing in eSports Gaming builds."
    meta_twitter_card = "summary"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
    name = "Projects"
    url = "/work/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
